Exercicio array person
Pedrohsantosg/nivelamento-bootcamp pull request #2
Opened 2024-10-01 02:11 UTC by Pedrohsantosg

2024-10-02 13:01 UTC, aLiviaMs requested changes

2024-10-02 13:01 UTC, aLiviaMs commented on exercicioNum01/index.html
Para próximos PRs, é importante ressaltar que caso vc crie uma branch a partir de outra branch, que acredito que tenha sido o caso (ex1 -> ex2) os commits gerados do ex1 são "herdadas" para esse tbm, em um fluxo de trabalho isso pode n ser mto bom.
Ademais, nesses casos vc pode direcionar seu PR para o ex1
Antes:
ex-2 -> main
Dps: ex-2 -> ex-1

2024-10-02 13:01 UTC, aLiviaMs commented on exercicioNum02/bio-name-remove-update.ts
> +type Descricao = string | undefined
Mesmo mudança sugerida no primeiro ex 
[> É interessante manter todo o seu código em uma mesma língua](https://github.com/Pedrohsantosg/nivelamento-bootcamp/pull/1#:~:text=46%20minutes%20ago-,%C3%89%20interessante%20manter%20todo%20o%20seu%20c%C3%B3digo%20em%20uma%20mesma%20l%C3%ADngua%2C%20minha%20sugest%C3%A3o%20%C3%A9%20sempre%20padronizar%20tudo%20para%20o%20ingl%C3%AAs%2C%20pois%20%C3%A9%20a%20maneira%20em%20que%20escrevemos%20nossos%20c%C3%B3digos%20em%2099%2C9%25%20do%20tempo%2C%20mas%20como%20s%C3%B3%20o%20nome%20dessa%20fun%C3%A7%C3%A3o%20est%C3%A1%20em%20ingl%C3%AAs%2C%20se%20preferir%20pode%20deixar%20tudo%20em%20portugu%C3%AAs,-Comment)

2024-10-02 13:01 UTC, aLiviaMs commented on exercicioNum02/bio-name-remove-update.ts
> +    let bioUser = ""
Mesma coisa do primeiro PR, manter a boa prática de [tipar as váriaveis](https://github.com/Pedrohsantosg/nivelamento-bootcamp/pull/1#:~:text=O%20c%C3%B3digo%20est%C3%A1,resto%20do%20algoritmo.) tbm.

2024-10-02 17:44 UTC, samuelcamilocosta requested changes

2024-10-02 17:44 UTC, samuelcamilocosta commented on exercicioNum02/bio-name-remove-update.ts
> +function getBioById(id: number): Descricao {
Você criou um type Descricao que é uma string ou indefinida e utilizou ele como retorno de várias funções.
A biografia é uma Descricao?
o name é uma Descrição?

Isso induz bastante ao erro para dar manutenção, colocar que o retorno pode ser uma `string | undefined` não tem problema, mas deixar o nome de Descrição pode causar bastante confusão no futuro, já que não é fácil supor que um name ou uma bio seja de fato uma Descrição

2024-10-02 17:44 UTC, samuelcamilocosta commented on exercicioNum02/bio-name-remove-update.ts
> +    } else {
Esse else é desnecessário. Pode removê-lo e deixar só o return false

2024-10-02 17:44 UTC, samuelcamilocosta commented on exercicioNum02/bio-name-remove-update.ts
> +            bioUser = "ID não encontrado."
id não encontrado ou seria biografia não encontrada?

2024-10-02 17:44 UTC, samuelcamilocosta commented on exercicioNum02/bio-name-remove-update.ts
> +function updatePersonById(id: number, newName?: string, newBio?: string): boolean {
o newName e o newBio tem a tipagem de string | undefined nas funções que você chamou, o parâmetro ? de opcional tem uma função além de permitir receber valores undefined e deve ser utilizado com cuidado

2024-10-02 17:44 UTC, samuelcamilocosta commented on exercicioNum02/bio-name-remove-update.ts
> +    } else {
Vou deixar como um bônus para ti aqui, pesquisar sobre Early Return Pattern, é uma prática comum que desenvolvedores utilizam e da um upgrade visual no código. :)

https://www.lucaspaganini.com/pt/academy/early-returns-code-patterns-in-javascript

2024-10-03 15:34 UTC, aLiviaMs approved these changes

2024-10-03 21:41 UTC, samuelcamilocosta commented
Sua branch está com conflitos, terá que corrigir eles para podermos mergear o exercício 2

2024-10-03 21:42 UTC, samuelcamilocosta approved these changes

2024-10-05 00:54 UTC, merged